using System.Text.Json.Serialization;

namespace AiTestCrew.Agents.Persistence;

using AiTestCrew.Agents.ApiAgent;
using AiTestCrew.Agents.AseXmlAgent;
using AiTestCrew.Agents.Shared;

/// <summary>
/// A single test objective within a test set — corresponds to one user objective.
/// Contains multiple test step definitions (API calls or UI test cases) that were
/// generated by the agent to fulfil the objective.
///
/// Hierarchy: Module > Test Set > Test Objective > Steps
/// </summary>
public class TestObjective
{
    /// <summary>Stable slug ID for correlation across runs (derived from name).</summary>
    public string Id { get; set; } = "";

    /// <summary>Human-readable display name for this objective.</summary>
    public string Name { get; set; } = "";

    /// <summary>The user's full original objective text that produced this test objective.</summary>
    public string ParentObjective { get; set; } = "";

    /// <summary>Name of the agent that generated/executes this objective.</summary>
    public string AgentName { get; set; } = "";

    /// <summary>Primary target type: "API_REST", "UI_Web_MVC", etc.</summary>
    public string TargetType { get; set; } = "API_REST";

    /// <summary>
    /// How this objective was created: "Generated" (AI/LLM) or "Recorded" (user recording).
    /// Recorded objectives cannot be rebaselined.
    /// </summary>
    public string Source { get; set; } = "Generated";

    /// <summary>
    /// API test step definitions — each is an individual HTTP request + assertions.
    /// Populated for API_REST / API_GraphQL targets.
    /// </summary>
    public List<ApiTestDefinition> ApiSteps { get; set; } = [];

    /// <summary>
    /// Web UI test step definitions — each is a self-contained UI test case with Playwright steps.
    /// Populated for UI_Web_* targets.
    /// </summary>
    public List<WebUiTestDefinition> WebUiSteps { get; set; } = [];

    /// <summary>
    /// Desktop UI test step definitions — each is a self-contained UI test case with FlaUI steps.
    /// Populated for UI_Desktop_* targets.
    /// </summary>
    public List<DesktopUiTestDefinition> DesktopUiSteps { get; set; } = [];

    /// <summary>
    /// aseXML generation test step definitions — each is a template id + user field values.
    /// Populated for AseXml_Generate targets.
    /// </summary>
    public List<AseXmlTestDefinition> AseXmlSteps { get; set; } = [];

    /// <summary>
    /// aseXML delivery test step definitions — template + user field values + endpoint code.
    /// Populated for AseXml_Deliver targets.
    /// </summary>
    public List<AseXmlDeliveryTestDefinition> AseXmlDeliverySteps { get; set; } = [];

    /// <summary>Total number of test steps in this objective.</summary>
    public int StepCount => ApiSteps.Count + WebUiSteps.Count + DesktopUiSteps.Count
        + AseXmlSteps.Count + AseXmlDeliverySteps.Count;

    /// <summary>
    /// Environment keys this objective is allowed to run on (e.g. "sumo-retail").
    /// Empty list means "default environment only" — legacy objectives created
    /// before the multi-env feature are treated this way by the orchestrator.
    /// To run an objective against additional environments, add env keys here
    /// and supply matching <see cref="EnvironmentParameters"/> entries.
    /// New objectives created/rebaselined by a run are auto-stamped with the active env key.
    /// </summary>
    public List<string> AllowedEnvironments { get; set; } = [];

    /// <summary>
    /// Per-environment {{Token}} → value overrides. Outer key = environment key
    /// (e.g. "sumo-retail"), inner key = token name (e.g. "NMI"), value = substitute.
    /// At playback, any <c>{{Token}}</c> literal in a step definition field is substituted
    /// with the value from the active environment's dictionary (lenient — unknown
    /// tokens remain as literals and are logged as WARN).
    /// </summary>
    public Dictionary<string, Dictionary<string, string>> EnvironmentParameters { get; set; } = new();

    // ── Backward compatibility for old v2 JSON with singular fields ──

    /// <summary>
    /// Old singular API definition — when deserialized from JSON, promotes into ApiSteps.
    /// Not serialized back out.
    /// </summary>
    [JsonPropertyName("apiDefinition")]
    public ApiTestDefinition? ApiDefinitionCompat
    {
        get => null; // never serialize
        set
        {
            if (value is not null && ApiSteps.Count == 0)
                ApiSteps.Add(value);
        }
    }

    /// <summary>
    /// Old singular Web UI definition — when deserialized from JSON, promotes into WebUiSteps.
    /// Not serialized back out.
    /// </summary>
    [JsonPropertyName("webUiDefinition")]
    public WebUiTestDefinition? WebUiDefinitionCompat
    {
        get => null; // never serialize
        set
        {
            if (value is not null && WebUiSteps.Count == 0)
                WebUiSteps.Add(value);
        }
    }

    /// <summary>
    /// Enumerates every post-step attached to any parent test step across all five
    /// step-list fields, yielding <c>(parentKind, parentStepIndex, postStepIndex, postStep)</c>.
    /// Used by <c>RunDispatchHelper</c> to decide whether a run needs a remote agent,
    /// and by the generalized record/edit flow to locate a post-step by coordinates.
    ///
    /// <c>parentKind</c> values: <c>"Api"</c>, <c>"WebUi"</c>, <c>"DesktopUi"</c>,
    /// <c>"AseXml"</c>, <c>"AseXmlDeliver"</c>.
    ///
    /// For <c>AseXmlDeliver</c>, yields entries from the legacy
    /// <c>PostDeliveryVerifications</c> field so back-compat behaviour is preserved
    /// until Slice 2 renames it.
    /// </summary>
    public IEnumerable<(string ParentKind, int ParentStepIndex, int PostStepIndex, VerificationStep PostStep)> EnumerateAllPostSteps()
    {
        for (var i = 0; i < ApiSteps.Count; i++)
        {
            var step = ApiSteps[i];
            for (var j = 0; j < step.PostSteps.Count; j++)
                yield return ("Api", i, j, step.PostSteps[j]);
        }
        for (var i = 0; i < WebUiSteps.Count; i++)
        {
            var step = WebUiSteps[i];
            for (var j = 0; j < step.PostSteps.Count; j++)
                yield return ("WebUi", i, j, step.PostSteps[j]);
        }
        for (var i = 0; i < DesktopUiSteps.Count; i++)
        {
            var step = DesktopUiSteps[i];
            for (var j = 0; j < step.PostSteps.Count; j++)
                yield return ("DesktopUi", i, j, step.PostSteps[j]);
        }
        for (var i = 0; i < AseXmlSteps.Count; i++)
        {
            var step = AseXmlSteps[i];
            for (var j = 0; j < step.PostSteps.Count; j++)
                yield return ("AseXml", i, j, step.PostSteps[j]);
        }
        for (var i = 0; i < AseXmlDeliverySteps.Count; i++)
        {
            var step = AseXmlDeliverySteps[i];
            // Legacy field — still canonical for delivery parents until Slice 2
            // rename. Yield via the same tuple shape so callers walk uniformly.
            for (var j = 0; j < step.PostSteps.Count; j++)
                yield return ("AseXmlDeliver", i, j, step.PostSteps[j]);
        }
    }
}
