using AiTestCrew.Agents.AseXmlAgent;

namespace AiTestCrew.Agents.ApiAgent;

/// <summary>
/// Represents a single API test case generated by the LLM.
/// </summary>
public class ApiTestCase
{
    public string Name { get; set; } = "";
    public string Method { get; set; } = "GET";
    public string Endpoint { get; set; } = "";
    public Dictionary<string, string> Headers { get; set; } = [];
    public Dictionary<string, string> QueryParams { get; set; } = [];
    public object? Body { get; set; }
    public int ExpectedStatus { get; set; } = 200;
    public List<string> ExpectedBodyContains { get; set; } = [];
    public List<string> ExpectedBodyNotContains { get; set; } = [];
    public bool IsFuzzTest { get; set; }

    /// <summary>
    /// Optional post-steps that run AFTER this API call completes. Mirrors the
    /// parent definition's field so the agent can see them when executing a
    /// preloaded reuse case.
    /// </summary>
    public List<VerificationStep> PostSteps { get; set; } = [];
}

/// <summary>
/// LLM's validation verdict on an API response.
/// </summary>
public class ApiValidation
{
    public bool Passed { get; set; }
    public string Reason { get; set; } = "";
    public List<string> Issues { get; set; } = [];
}