using AiTestCrew.Agents.AseXmlAgent;

namespace AiTestCrew.Agents.ApiAgent;

/// <summary>
/// Represents a single API test case generated by the LLM or authored via the
/// editor / skill. Mirrors <see cref="ApiTestDefinition"/> but carries a Name
/// and is the runtime-execution shape (used in reuse mode as
/// <c>PreloadedTestCases</c>).
/// </summary>
public class ApiTestCase
{
    public string Name { get; set; } = "";
    public string Method { get; set; } = "GET";
    public string Endpoint { get; set; } = "";
    public Dictionary<string, string> Headers { get; set; } = [];
    public Dictionary<string, string> QueryParams { get; set; } = [];
    public object? Body { get; set; }
    public int ExpectedStatus { get; set; } = 200;
    public List<string> ExpectedBodyContains { get; set; } = [];
    public List<string> ExpectedBodyNotContains { get; set; } = [];
    public bool IsFuzzTest { get; set; }

    // ── REQ-007: structured assertions and captures ──────────────────────────────

    /// <summary>
    /// Operator-driven assertions on the response. When non-empty, these are
    /// authoritative and the LLM validation step is skipped. Promoted from
    /// legacy fields via <see cref="ApiTestDefinition.NormaliseLegacyFields"/>
    /// during definition → test-case conversion.
    /// </summary>
    public List<ApiAssertion> ApiAssertions { get; set; } = [];

    /// <summary>
    /// Captures scalar values from the HTTP response into the per-objective
    /// post-step run context as <c>{{Token}}</c> entries.
    /// </summary>
    public List<ApiCapture> Captures { get; set; } = [];

    /// <summary>
    /// Optional post-steps that run AFTER this API call completes. Mirrors the
    /// parent definition's field so the agent can see them when executing a
    /// preloaded reuse case.
    /// </summary>
    public List<VerificationStep> PostSteps { get; set; } = [];
}

/// <summary>
/// LLM's validation verdict on an API response.
/// </summary>
public class ApiValidation
{
    public bool Passed { get; set; }
    public string Reason { get; set; } = "";
    public List<string> Issues { get; set; } = [];
}
