namespace AiTestCrew.Agents.Shared;

/// <summary>
/// A single web UI test case generated by an LLM from a natural language objective.
/// Stored as JSON and replayed deterministically on reuse runs.
/// </summary>
public class WebUiTestCase
{
    /// <summary>Short descriptive name for this test case.</summary>
    public string Name { get; set; } = "";

    /// <summary>Human-readable description of what this test case verifies.</summary>
    public string Description { get; set; } = "";

    /// <summary>
    /// Starting URL for this test case — relative (e.g. "/login") or absolute.
    /// If relative, it is resolved against the agent's TargetBaseUrl.
    /// </summary>
    public string StartUrl { get; set; } = "";

    /// <summary>Ordered list of Playwright steps to execute.</summary>
    public List<WebUiStep> Steps { get; set; } = [];

    /// <summary>When true, a screenshot is saved to PlaywrightScreenshotDir on step failure.</summary>
    public bool TakeScreenshotOnFailure { get; set; } = true;
}

/// <summary>
/// A single Playwright action within a <see cref="WebUiTestCase"/>.
/// </summary>
public class WebUiStep
{
    /// <summary>
    /// Action to perform. Allowed values:
    ///   navigate          — go to a URL (Value = URL)
    ///   click             — click an element (Selector required)
    ///   fill              — type text into an input (Selector + Value required)
    ///   select            — pick an option from a select element (Selector + Value required)
    ///   check             — tick a checkbox (Selector required)
    ///   uncheck           — untick a checkbox (Selector required)
    ///   hover             — hover over an element (Selector required)
    ///   press             — send a keyboard key (Selector optional, Value = key name e.g. "Enter")
    ///   assert-text       — assert element's visible text contains Value (Selector + Value required)
    ///   assert-visible    — assert element is visible (Selector required)
    ///   assert-hidden     — assert element is not visible (Selector required)
    ///   assert-url-contains    — assert current URL contains Value (Value required)
    ///   assert-title-contains  — assert page title contains Value (Value required)
    ///   wait              — wait for selector to appear (Selector required)
    ///   wait-for-stable   — wait until DOM mutations stop for N ms (Value = ms threshold, default 1000)
    /// </summary>
    public string Action { get; set; } = "";

    /// <summary>CSS or XPath selector identifying the target element (where required).</summary>
    public string? Selector { get; set; }

    /// <summary>
    /// Context-specific value:
    ///   fill → text to type
    ///   select → option value/label
    ///   navigate → URL
    ///   press → key name
    ///   assert-text / assert-url-contains / assert-title-contains → expected substring
    /// </summary>
    public string? Value { get; set; }

    /// <summary>Per-step timeout in milliseconds. Defaults to 5000 ms.</summary>
    public int TimeoutMs { get; set; } = 5000;
}
