using AiTestCrew.Core.Interfaces;

namespace AiTestCrew.WebApi.Services;

/// <summary>
/// Writes capability-gap stub requirement files to the working copy.
/// Scans requirements/ for the highest existing REQ number and increments.
/// Files are NOT committed -- they land on disk for the QA to review.
/// </summary>
public class GapRequirementWriter
{
    private readonly string _requirementsDir;
    private readonly ILogger<GapRequirementWriter> _logger;

    public GapRequirementWriter(string requirementsDir, ILogger<GapRequirementWriter> logger)
    {
        _requirementsDir = requirementsDir;
        _logger = logger;
    }

    /// <summary>
    /// Writes a stub REQ file for an unsupported Xray step.
    /// Returns the absolute path to the written file.
    /// </summary>
    public string Write(GapReqSpec spec)
    {
        int nextNum = FindNextReqNumber();
        string slug = ToSlug(spec.SuggestedTitle);
        string id = "REQ-" + nextNum.ToString("D3");
        string fileName = id + "-" + slug + ".md";
        string path = Path.Combine(_requirementsDir, fileName);
        string today = DateTime.UtcNow.ToString("yyyy-MM-dd");

        var sb = new System.Text.StringBuilder();
        sb.AppendLine("---");
        sb.AppendLine("id: " + id);
        sb.AppendLine("title: " + spec.SuggestedTitle);
        sb.AppendLine("status: Proposed");
        sb.AppendLine("created: " + today);
        sb.AppendLine("author: Auto-generated from Xray import");
        sb.AppendLine("area: " + spec.Area);
        sb.AppendLine("source-ticket: " + spec.TicketKey);
        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine("# " + id + " -- " + spec.SuggestedTitle);
        sb.AppendLine();
        sb.AppendLine("## Goal");
        sb.AppendLine();
        sb.AppendLine(spec.Rationale);
        sb.AppendLine();
        sb.AppendLine("## Source of need");
        sb.AppendLine();
        sb.AppendLine("This requirement was auto-generated by the Xray importer (REQ-017) when importing **" + spec.TicketKey + "** (“" + spec.TicketSummary + "”) on " + today + ". The Xray step below was identified as outside AITestCrew current capabilities:");
        sb.AppendLine();
        sb.AppendLine("> " + spec.StepText);
        sb.AppendLine();
        sb.AppendLine("## Why now");
        sb.AppendLine();
        sb.AppendLine("This capability gap was surfaced during automated Xray import. Without this primitive, the corresponding Xray test step cannot be executed by AITestCrew and must remain as a manual test.");
        sb.AppendLine();
        sb.AppendLine("## Proposed direction (sketch -- to be refined by tooling team)");
        sb.AppendLine();
        sb.AppendLine(spec.SuggestedExtensionPoint);
        sb.AppendLine();
        sb.AppendLine("## Acceptance criteria (skeleton)");
        sb.AppendLine();
        sb.AppendLine("1. (fill in)");
        sb.AppendLine("2. (fill in)");
        sb.AppendLine();
        sb.AppendLine("## Out of scope");
        sb.AppendLine();
        sb.AppendLine("- (fill in)");
        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine("*This stub was auto-generated. A human must review the goal, refine the proposed direction, and fill in acceptance criteria before this requirement is workable.*");

        Directory.CreateDirectory(_requirementsDir);
        File.WriteAllText(path, sb.ToString(), System.Text.Encoding.UTF8);
        _logger.LogInformation("Gap REQ written: {Path}", path);
        return path;
    }

    private int FindNextReqNumber()
    {
        if (!Directory.Exists(_requirementsDir))
            return 1;

        int max = 0;
        foreach (var file in Directory.GetFiles(_requirementsDir, "REQ-*.md"))
        {
            var name = Path.GetFileNameWithoutExtension(file);
            if (name.Length >= 7 && name.StartsWith("REQ-") && int.TryParse(name.Substring(4, 3), out int n))
                max = Math.Max(max, n);
        }
        return max + 1;
    }

    private static string ToSlug(string title)
    {
        var slug = title.ToLowerInvariant();
        slug = System.Text.RegularExpressions.Regex.Replace(slug, "[^a-z0-9]+", "-");
        slug = slug.Trim('-');
        if (slug.Length > 50) slug = slug[..50].TrimEnd('-');
        return slug;
    }
}