using System.Text.Json.Serialization;

namespace AiTestCrew.Agents.Persistence;

using AiTestCrew.Agents.ApiAgent;
using AiTestCrew.Agents.Shared;

/// <summary>
/// A single test objective within a test set — corresponds to one user objective.
/// Contains multiple test step definitions (API calls or UI test cases) that were
/// generated by the agent to fulfil the objective.
///
/// Hierarchy: Module > Test Set > Test Objective > Steps
/// </summary>
public class TestObjective
{
    /// <summary>Stable slug ID for correlation across runs (derived from name).</summary>
    public string Id { get; set; } = "";

    /// <summary>Human-readable display name for this objective.</summary>
    public string Name { get; set; } = "";

    /// <summary>The user's full original objective text that produced this test objective.</summary>
    public string ParentObjective { get; set; } = "";

    /// <summary>Name of the agent that generated/executes this objective.</summary>
    public string AgentName { get; set; } = "";

    /// <summary>Primary target type: "API_REST", "UI_Web_MVC", etc.</summary>
    public string TargetType { get; set; } = "API_REST";

    /// <summary>
    /// How this objective was created: "Generated" (AI/LLM) or "Recorded" (user recording).
    /// Recorded objectives cannot be rebaselined.
    /// </summary>
    public string Source { get; set; } = "Generated";

    /// <summary>
    /// API test step definitions — each is an individual HTTP request + assertions.
    /// Populated for API_REST / API_GraphQL targets.
    /// </summary>
    public List<ApiTestDefinition> ApiSteps { get; set; } = [];

    /// <summary>
    /// Web UI test step definitions — each is a self-contained UI test case with Playwright steps.
    /// Populated for UI_Web_* targets.
    /// </summary>
    public List<WebUiTestDefinition> WebUiSteps { get; set; } = [];

    /// <summary>
    /// Desktop UI test step definitions — each is a self-contained UI test case with FlaUI steps.
    /// Populated for UI_Desktop_* targets.
    /// </summary>
    public List<DesktopUiTestDefinition> DesktopUiSteps { get; set; } = [];

    /// <summary>Total number of test steps in this objective.</summary>
    public int StepCount => ApiSteps.Count + WebUiSteps.Count + DesktopUiSteps.Count;

    // ── Backward compatibility for old v2 JSON with singular fields ──

    /// <summary>
    /// Old singular API definition — when deserialized from JSON, promotes into ApiSteps.
    /// Not serialized back out.
    /// </summary>
    [JsonPropertyName("apiDefinition")]
    public ApiTestDefinition? ApiDefinitionCompat
    {
        get => null; // never serialize
        set
        {
            if (value is not null && ApiSteps.Count == 0)
                ApiSteps.Add(value);
        }
    }

    /// <summary>
    /// Old singular Web UI definition — when deserialized from JSON, promotes into WebUiSteps.
    /// Not serialized back out.
    /// </summary>
    [JsonPropertyName("webUiDefinition")]
    public WebUiTestDefinition? WebUiDefinitionCompat
    {
        get => null; // never serialize
        set
        {
            if (value is not null && WebUiSteps.Count == 0)
                WebUiSteps.Add(value);
        }
    }
}
