namespace AiTestCrew.Agents.Shared;

/// <summary>
/// A single desktop UI test case generated by an LLM or captured via desktop recording.
/// Stored as JSON and replayed deterministically on reuse runs using FlaUI (UI Automation).
/// </summary>
public class DesktopUiTestCase
{
    /// <summary>Short descriptive name for this test case.</summary>
    public string Name { get; set; } = "";

    /// <summary>Human-readable description of what this test case verifies.</summary>
    public string Description { get; set; } = "";

    /// <summary>Ordered list of desktop UI steps to execute.</summary>
    public List<DesktopUiStep> Steps { get; set; } = [];

    /// <summary>When true, a screenshot is saved to WinFormsScreenshotDir on step failure.</summary>
    public bool TakeScreenshotOnFailure { get; set; } = true;
}

/// <summary>
/// A single desktop UI action within a <see cref="DesktopUiTestCase"/>.
/// Elements are located using a composite selector with cascading fallback:
/// AutomationId → Name → ClassName+ControlType → TreePath.
/// </summary>
public class DesktopUiStep
{
    /// <summary>
    /// Action to perform. Allowed values:
    ///   click             — click an element
    ///   double-click      — double-click an element
    ///   right-click       — right-click an element
    ///   fill              — type text into an input (Value = text to type)
    ///   select            — pick an item from a combo box (Value = item text)
    ///   check             — tick a checkbox
    ///   uncheck           — untick a checkbox
    ///   press             — send a keyboard key (Value = key name e.g. "Enter", "Tab")
    ///   hover             — hover over an element
    ///   assert-text       — assert element's text contains Value
    ///   assert-visible    — assert element is visible (not off-screen)
    ///   assert-hidden     — assert element is not visible
    ///   assert-enabled    — assert element is enabled
    ///   assert-disabled   — assert element is disabled
    ///   wait-for-window   — wait for a window with matching WindowTitle to appear
    ///   switch-window     — set focus to a window matching WindowTitle
    ///   close-window      — close a window matching WindowTitle
    ///   menu-navigate     — walk a menu bar chain (MenuPath = "File > Save As")
    ///   wait              — wait for an element to appear or a fixed delay (Value = ms)
    /// </summary>
    public string Action { get; set; } = "";

    /// <summary>
    /// UI Automation AutomationId — highest priority selector.
    /// Most stable identifier for WinForms controls (maps to Control.Name property in code).
    /// </summary>
    public string? AutomationId { get; set; }

    /// <summary>
    /// UI Automation Name property — second priority selector.
    /// Typically the visible text/label of the control.
    /// </summary>
    public string? Name { get; set; }

    /// <summary>
    /// UI Automation ClassName — third priority selector (used with ControlType).
    /// e.g. "WindowsForms10.EDIT.app.0.141b42a_r6_ad1" or "Button".
    /// </summary>
    public string? ClassName { get; set; }

    /// <summary>
    /// UI Automation ControlType — third priority selector (used with ClassName).
    /// e.g. "Button", "Edit", "ComboBox", "CheckBox", "DataGrid", "MenuItem", "Window".
    /// </summary>
    public string? ControlType { get; set; }

    /// <summary>
    /// Fallback tree path from window root — lowest priority selector.
    /// Format: "Window/Pane[0]/Button[2]" — indexed path through the automation tree.
    /// </summary>
    public string? TreePath { get; set; }

    /// <summary>
    /// Context-specific value:
    ///   fill → text to type
    ///   select → item text to pick
    ///   press → key name (e.g. "Enter", "Tab", "Escape")
    ///   assert-text → expected substring
    ///   wait → milliseconds (when no element selector is provided)
    /// </summary>
    public string? Value { get; set; }

    /// <summary>
    /// For menu-navigate action: chain of menu item names separated by " > ".
    /// e.g. "File > Save As" or "Edit > Preferences > General".
    /// </summary>
    public string? MenuPath { get; set; }

    /// <summary>
    /// For wait-for-window / switch-window / close-window actions:
    /// title pattern (substring match) of the target window.
    /// </summary>
    public string? WindowTitle { get; set; }

    /// <summary>Per-step timeout in milliseconds. Defaults to 5000 ms.</summary>
    public int TimeoutMs { get; set; } = 5000;

    /// <summary>
    /// Screen X of the recorded click, relative to the main window's top-left.
    /// Used as a coordinate-based fallback when the element cannot be resolved
    /// via UIA (e.g. legacy WinForms CheckedComboBox popups that render
    /// visually but do not expose their items in the UI Automation tree).
    /// Null for steps that weren't captured via a mouse click (fills, asserts,
    /// keypresses) and for pre-existing recordings made before this field existed.
    /// </summary>
    public int? WindowRelativeX { get; set; }

    /// <summary>
    /// Screen Y of the recorded click, relative to the main window's top-left.
    /// See <see cref="WindowRelativeX"/> for usage.
    /// </summary>
    public int? WindowRelativeY { get; set; }

    /// <summary>
    /// Milliseconds the user paused on this step during recording (delta
    /// from the previous step's capture time). Replay honours this delay
    /// *before* executing the step, so recorded pacing — e.g. waiting for
    /// a search to complete or a menu to animate in — is preserved
    /// automatically without needing explicit wait steps.
    /// Null for pre-existing recordings made before this field existed;
    /// the executor treats null as "no delay".
    /// Capped at a sane maximum on replay to avoid pathological hangs.
    /// </summary>
    public int? DelayBeforeMs { get; set; }
}
